# Generated by Django 2.1.5 on 2019-01-14 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=70)),
                ('date_of_appraisal', models.CharField(default=None, max_length=40)),
                ('who_appraised', models.CharField(default=None, max_length=80)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.Employee')),
            ],
        ),
    ]
