# Generated by Django 2.1.5 on 2019-01-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='date_of_appraisal',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='target',
            name='who_appraised',
            field=models.CharField(max_length=80),
        ),
    ]
