# Generated by Django 2.1.5 on 2019-01-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20190114_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(default='incomplete', max_length=70),
        ),
    ]
