# Generated by Django 2.1.3 on 2018-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
