# Generated by Django 2.1.5 on 2019-01-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='period',
        ),
        migrations.AddField(
            model_name='applyleave',
            name='period',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.Employee'),
        ),
    ]
