# Generated by Django 2.1.5 on 2019-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20190129_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='employee',
            field=models.CharField(max_length=200),
        ),
    ]
