# Generated by Django 2.1.5 on 2019-01-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('accounts', '0001_initial'),
        ('leave', '0002_applyleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='departments.Department'),
        ),
        migrations.AddField(
            model_name='applyleave',
            name='home_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applyleave',
            name='person_taking_charge',
            field=models.ForeignKey(default='hr', on_delete=django.db.models.deletion.CASCADE, related_name='person_charge', to='accounts.Employee'),
        ),
        migrations.AddField(
            model_name='applyleave',
            name='resume_date',
            field=models.DateField(default='1/1/2018'),
        ),
    ]
