# Generated by Django 2.1.5 on 2019-01-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20190108_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='departments.Department'),
        ),
    ]
