# Generated by Django 2.1.5 on 2019-01-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190108_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='home_phone',
            field=models.IntegerField(default=70000111),
        ),
    ]
