# Generated by Django 2.1.5 on 2019-02-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190214_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='leave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='leave.Leave'),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='person_taking_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_taking', to='accounts.Employee'),
        ),
    ]
