# Generated by Django 2.1.5 on 2019-03-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_applyleave_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='leave',
            field=models.CharField(choices=[(1, 'Sick Leave')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='person_taking_charge',
            field=models.CharField(choices=[(1, 'OmambiaDauglous'), (4, 'FaizaJoyK'), (5, 'EverlineCherry'), (6, 'JohnSmith'), (7, 'OmambiaMogaka'), (8, 'JoiceOtieno')], default=1, max_length=100),
        ),
    ]
