# Generated by Django 2.1.5 on 2019-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20190108_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
