# Generated by Django 2.1.5 on 2019-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20190108_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='home_phone',
            field=models.IntegerField(),
        ),
    ]
