# Generated by Django 2.1.5 on 2019-01-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20190108_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleave',
            name='department',
        ),
    ]
