# Generated by Django 2.1.5 on 2019-01-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_applyleave_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleave',
            name='department',
        ),
    ]
