# Generated by Django 2.1.5 on 2019-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_remove_applyleave_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
