# Generated by Django 2.1.5 on 2019-01-11 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_auto_20190111_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='person_taking_charge',
            field=models.CharField(default='Department Head', max_length=50),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='resume_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
