# Generated by Django 2.1.5 on 2019-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_auto_20190111_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='status',
            field=models.IntegerField(),
        ),
    ]
