# Generated by Django 2.1.5 on 2019-01-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20190111_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='person_taking_charge',
            field=models.CharField(default='HOD', max_length=50),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='resume_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
