# Generated by Django 2.1.5 on 2019-04-09 09:55

import Legal.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('dofsigning', models.DateField(default=datetime.datetime.now)),
                ('doflasping', models.DateField(default=datetime.datetime.now)),
                ('document', models.FileField(blank=True, upload_to=Legal.models.UploadFolder('documents/legal'))),
                ('description', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GS1Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('dated', models.DateField(default=datetime.datetime.now)),
                ('documents', models.FileField(blank=True, upload_to=Legal.models.UploadFolder('documents/legal'))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('dated', models.DateField(default=datetime.datetime.now)),
                ('documents', models.FileField(blank=True, upload_to=Legal.models.UploadFolder('documents/legal'))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
