# Generated by Django 2.1.5 on 2019-04-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Legal.Category'),
        ),
    ]
