# Generated by Django 2.1.5 on 2019-04-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0002_contract_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='documents',
            new_name='document',
        ),
    ]
