# Generated by Django 2.1.5 on 2019-04-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0003_auto_20190409_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gs1docs',
            old_name='documents',
            new_name='document',
        ),
    ]
