# Generated by Django 2.1.5 on 2019-04-09 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0004_auto_20190409_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
