# Generated by Django 2.1.5 on 2019-04-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0005_category_dated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='doflasping',
            new_name='doflapsing',
        ),
    ]
