# Generated by Django 2.1.5 on 2019-04-12 12:23

import Legal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0007_auto_20190410_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(upload_to=Legal.models.UploadFolder('documents/legal')),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gs1docs',
            name='document',
            field=models.FileField(upload_to=Legal.models.UploadFolder('documents/legal')),
        ),
        migrations.AlterField(
            model_name='gs1docs',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='document',
            field=models.FileField(upload_to=Legal.models.UploadFolder('documents/legal')),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
