# Generated by Django 2.1.5 on 2019-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='kin_email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
