# Generated by Django 2.1.5 on 2019-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=30),
        ),
    ]
