# Generated by Django 2.1.5 on 2019-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_leave_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_bal',
            field=models.IntegerField(default=4),
        ),
    ]
