# Generated by Django 2.1.5 on 2019-02-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_leave_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_benifits',
            field=models.CharField(default='Pay NHIF, NSSF', max_length=1000),
        ),
    ]
