# Generated by Django 2.1.5 on 2019-02-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190226_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.Position'),
        ),
    ]
