# Generated by Django 2.1.5 on 2019-02-27 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190227_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='alt_phone_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9)]),
        ),
    ]
