# Generated by Django 2.1.5 on 2019-03-20 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190227_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='KRA',
            field=models.CharField(default='KRA_PIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_phone_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(9)]),
        ),
    ]
