# Generated by Django 2.1.5 on 2019-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190320_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_bal',
            field=models.IntegerField(default=21),
        ),
    ]
