# Generated by Django 2.1.5 on 2019-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_employee_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_bal',
            field=models.PositiveIntegerField(blank=True, default=21),
        ),
    ]
