# Generated by Django 2.1.5 on 2019-04-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
    ]
