# Generated by Django 2.1.5 on 2019-03-06 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_auto_20190227_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('finish_date', models.DateField()),
                ('objective', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='accounts.Employee')),
            ],
        ),
    ]
