# Generated by Django 2.1.5 on 2019-03-04 04:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_generate', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=2000)),
                ('VAT', models.CharField(choices=[(1, 'Yes'), (0, 'No')], default='No', max_length=5)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM.Client')),
            ],
        ),
    ]
