# Generated by Django 2.1.5 on 2019-03-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='VAT',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
