# Generated by Django 2.1.5 on 2019-03-07 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190227_0920'),
        ('ACCNTS', '0003_auto_20190305_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_allowance', models.IntegerField(default=0)),
                ('leave_allowance', models.IntegerField(default=0)),
                ('hse_allowance', models.IntegerField(default=0)),
                ('loans', models.IntegerField(default=0)),
                ('other_deductions', models.IntegerField(default=0)),
                ('month', models.DateField(default=datetime.datetime.now)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
    ]
