# Generated by Django 2.1.5 on 2019-03-20 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0006_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_due',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
