# Generated by Django 2.1.5 on 2019-03-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0007_auto_20190320_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='amount_paid',
        ),
    ]
