# Generated by Django 2.1.5 on 2019-03-21 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20190319_0815'),
        ('ACCNTS', '0008_remove_sales_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField(default=datetime.datetime.now)),
                ('memo', models.CharField(max_length=1000)),
                ('bill_due', models.DateField(default=datetime.datetime.now)),
                ('terms_of_payment', models.CharField(choices=[('Pay immediately', 'Pay immediately'), ('Bill in 10 days', 'Bill in 10 days'), ('Bill in 20 days', 'Bill in 20 days'), ('Bill in 30 days', 'Bill in 30 days'), ('Bill in 60 days', 'Bill in 60 days')], default='Pay Immediately', max_length=100)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('bank cheque', 'Bank cheque'), ('cash', 'Cash')], default='Bank Cheque', max_length=200)),
                ('VAT', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10)),
                ('ref_no', models.CharField(blank=True, max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('expense_type', models.CharField(choices=[('operational', 'Operational')], default='operational', max_length=100)),
                ('vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM.Supplier')),
            ],
        ),
    ]
