# Generated by Django 2.1.5 on 2019-03-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0009_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='hse_allowance',
            new_name='lunch',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='leave_allowance',
            new_name='pension',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='transport_allowance',
        ),
    ]
