# Generated by Django 2.1.5 on 2019-03-27 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190320_0843'),
        ('ACCNTS', '0010_auto_20190326_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('current', 'Current'), ('fixed', 'Fixed')], default='current', max_length=200)),
                ('open_balance', models.IntegerField(blank=True, default=0)),
                ('amount', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(default=0)),
                ('month', models.DateField(default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('giver', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('other incomes', 'Other incomes'), ('direct income', 'Direct income')], default='direct income', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('open_balance', models.IntegerField(blank=True, default=0)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('current', 'Current'), ('short-term', 'Short-term')], default='current', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('open_balance', models.IntegerField(blank=True, default=0)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
    ]
