# Generated by Django 2.1.5 on 2019-03-29 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0011_asset_employeetax_income_liability'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dated',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='income',
            name='dated',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='liability',
            name='dated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
