# Generated by Django 2.1.5 on 2019-04-04 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0012_auto_20190329_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Payment', 'Payment'), ('Sales Receipt', 'Sales reciept')], default='Payment', max_length=50)),
                ('ref_number', models.CharField(max_length=100)),
                ('dated', models.DateField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=200)),
                ('banked', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
