# Generated by Django 2.1.5 on 2019-04-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190417_1142'),
        ('ACCNTS', '0013_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf', models.IntegerField()),
                ('nhif', models.IntegerField()),
                ('nhsb', models.IntegerField()),
                ('paye', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
    ]
