# Generated by Django 2.1.5 on 2019-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0014_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetax',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeTax',
        ),
    ]
