# Generated by Django 2.1.5 on 2019-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0016_payroll_is_taxed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='is_taxed',
            field=models.BooleanField(default=False),
        ),
    ]
