# Generated by Django 2.1.5 on 2019-04-17 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0018_deduction_dated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='dated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
