# Generated by Django 2.1.5 on 2019-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0019_auto_20190417_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
