# Generated by Django 2.1.5 on 2019-04-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_member'),
        ('ACCNTS', '0020_auto_20190423_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM.Member'),
        ),
    ]
