# Generated by Django 2.1.5 on 2019-04-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCNTS', '0021_income_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='name',
        ),
    ]
