# Generated by Django 2.1.5 on 2019-01-30 15:48

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_employee_alt_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_file', models.FileField(upload_to=payroll.models.UploadFolder('documents/payroll'))),
                ('created_on', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='accounts.Employee')),
            ],
        ),
    ]
