# Generated by Django 2.1.5 on 2019-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.IntegerField()),
                ('company_phone_alt', models.IntegerField()),
                ('company_email', models.CharField(max_length=128)),
                ('company_email_alt', models.CharField(max_length=128)),
                ('post_address', models.CharField(max_length=200)),
                ('physical_location', models.CharField(max_length=60)),
                ('director_info', models.CharField(max_length=1000)),
                ('sector', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=80)),
                ('date_of_issue', models.DateField()),
                ('nature_of_business', models.CharField(max_length=100)),
            ],
        ),
    ]
