# Generated by Django 2.1.5 on 2019-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[(150000, '150000'), (200000, '200000'), (3000050000, '3000050000'), (20000, '20000')], default='No category', max_length=80),
        ),
    ]
