# Generated by Django 2.1.5 on 2019-01-25 10:30

import CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='copy_of_blank_cheque',
            field=models.FileField(default=0, upload_to=CRM.models.UploadFolder('/documents/clients')),
        ),
    ]
