# Generated by Django 2.1.5 on 2019-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=40)),
                ('website', models.URLField(blank=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
