# Generated by Django 2.1.5 on 2019-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(default=0)),
                ('is_me1', models.IntegerField(default=0)),
                ('is_me2', models.IntegerField(default=0)),
                ('is_ccm', models.IntegerField(default=0)),
                ('is_accm', models.IntegerField(default=0)),
                ('is_cacc', models.IntegerField(default=0)),
                ('is_tm', models.IntegerField(default=0)),
                ('is_gm', models.IntegerField(default=0)),
            ],
        ),
    ]
