# Generated by Django 2.1.5 on 2019-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20190305_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.PositiveIntegerField(choices=[(150000, '150000'), (200000, '200000'), (3000050000, '3000050000'), (20000, '20000')], default=20000),
        ),
    ]
