# Generated by Django 2.1.5 on 2019-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_clientapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapproval',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
