# Generated by Django 2.1.5 on 2019-01-25 10:49

import CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20190125_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='client_name',
            new_name='trainer',
        ),
        migrations.AlterField(
            model_name='client',
            name='certificate_of_incorporation',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_certificate_pin',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_blank_cheque',
            field=models.FileField(default=0, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_id',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_kebs_certicate',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_trade_licence',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='director_pin_number',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='list_of_product_barcoded',
            field=models.FileField(upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
    ]
