# Generated by Django 2.1.5 on 2019-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20190120_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='certificate_of_incorporation',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_certificate_pin',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='copy_of_blank_cheque',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='copy_of_id',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='copy_of_kebs_certicate',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='copy_of_trade_licence',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='director_pin_number',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='client',
            name='list_of_product_barcoded',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
    ]
