# Generated by Django 2.1.5 on 2019-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20190305_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
