# Generated by Django 2.1.5 on 2019-02-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_clientapproval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='client',
        ),
        migrations.DeleteModel(
            name='ClientApproval',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='client_name',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainer',
        ),
        migrations.AddField(
            model_name='client',
            name='is_accm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='is_cacc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='is_ccm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='is_gm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='is_me1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='is_me2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='is_tm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
