# Generated by Django 2.1.5 on 2019-03-11 03:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20190310_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='all_trainee',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'BrugKe'), (2, 'gs1'), (3, 'omambia')], max_length=3, null=True),
        ),
    ]
