# Generated by Django 2.1.5 on 2019-01-25 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_feedback_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='happened_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='training',
            name='number_of_trainee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
