# Generated by Django 2.1.5 on 2019-03-19 08:15

import CRM.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20190311_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='certificate_of_incorporation',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_certificate_pin',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_blank_cheque',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_kebs_certicate',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='copy_of_trade_licence',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='director_pin_number',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='client',
            name='list_of_product_barcoded',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
        migrations.AlterField(
            model_name='training',
            name='all_trainee',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'gs1'), (3, 'omambia')], max_length=3, null=True),
        ),
    ]
