# Generated by Django 2.1.5 on 2019-02-21 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20190218_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('date_time', models.DateField(default=datetime.datetime.now)),
                ('status', models.IntegerField(default=0)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trian', to='CRM.Training')),
            ],
        ),
    ]
