# Generated by Django 2.1.5 on 2019-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20190125_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
