# Generated by Django 2.1.5 on 2019-04-16 08:51

import CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20190319_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='copy_of_id',
            field=models.FileField(blank=True, upload_to=CRM.models.UploadFolder('documents/clients')),
        ),
    ]
