# Generated by Django 2.1.5 on 2019-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default='omambia', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='Omambia', max_length=200),
            preserve_default=False,
        ),
    ]
