# Generated by Django 2.1.5 on 2019-01-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20190127_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='topic',
        ),
    ]
