# Generated by Django 2.1.5 on 2019-04-16 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20190416_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
