# Generated by Django 2.1.5 on 2019-02-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_auto_20190221_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='name',
        ),
    ]
