# Generated by Django 2.1.5 on 2019-02-07 07:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_remove_training_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='all_trainee',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'BrugKe')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
