# Generated by Django 2.1.5 on 2019-04-18 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190417_1142'),
        ('CRM', '0009_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateTimeField(default=datetime.datetime.now)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Client')),
            ],
        ),
    ]
