# Generated by Django 2.1.5 on 2019-02-10 03:47

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_training_all_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTIN', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('name_packaging', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('depth', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('gross_weight', models.CharField(max_length=50)),
                ('net_weight', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='all_trainee',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'BrugKe'), (2, 'gs1')], max_length=3),
        ),
    ]
