# Generated by Django 2.1.5 on 2019-02-26 12:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_remove_training_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='number_of_trainee',
        ),
        migrations.AlterField(
            model_name='training',
            name='all_trainee',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'BrugKe'), (2, 'gs1')], max_length=3, null=True),
        ),
    ]
