# Generated by Django 2.1.5 on 2019-02-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_auto_20190210_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='depth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='name_packaging',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='net_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='width',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
