# Generated by Django 2.1.5 on 2019-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_auto_20190210_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
