# Generated by Django 2.1.5 on 2019-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_barcode_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='size',
            field=models.IntegerField(blank=True),
        ),
    ]
