# Generated by Django 2.1.5 on 2019-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_auto_20190214_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
