# Generated by Django 2.1.5 on 2019-02-07 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='created_on',
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='departments.Department'),
            preserve_default=False,
        ),
    ]
