# Generated by Django 2.1.5 on 2019-02-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20190207_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='departments.Department'),
        ),
    ]
